apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  labels:
    app: spring-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-oauth
  template:
    metadata:
      labels:
        app: spring-oauth
    spec:
      containers:
        - name: spring-oauth
          image: lathgr/spring-oauth:${{ github.run_number }}

          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-oauth-service
  labels:
    app: spring-oauth
spec:
  type: LoadBalancer
  selector:
    app: spring-oauth
  ports:
    - port: 8080
      targetPort: 8080
